version: "3.7"
services:
    web_app:
        build: .
        restart: always
        ports: 
            - "8001:80"
        volumes:
            - ./app:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7
        container_name: mysql_container
        restart: always
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: budget_calculator
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - persistent:/var/lib/mysql
            - ./budget_calculator.sql:/docker-entrypoint-initdb.d/budget_calculator.sql
            
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: